server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: book-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/books/**
          filters:
            - StripPrefix=2
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=2
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=2
        - id: rental-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/rentals/**
          filters:
            - StripPrefix=2
        - id: report-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/reports/**
          filters:
            - StripPrefix=2
        - id: auth-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
